version: "3.9"

services:
  ngrok:
    image: ngrok/ngrok:3.1.0-alpine
    command: start --all
    environment:
      - NGROK_CONFIG=/etc/ngrok.yml
      - NGROK_AUTHTOKEN=${NGROK_TOKEN}
    ports:
      - "4040:4040"
    volumes:
      - ./network/ngrok.yml:/etc/ngrok.yml

  # TODO: add postgres storage

  framework.dvla:
    build:
      dockerfile: ./network/Dockerfile.framework
    entrypoint: /scripts/start-framework.sh
    environment:
      - AGENT_LABEL=DVLA Agent
      - FRAMEWORK_PORT=8000
      - ADMIN_PORT=8001
      - ADMIN_SECRET=${DVLA_ADMIN_SECRET}
      - CONTROLLER_HOST=controller.dvla
      - CONTROLLER_PORT=8002
      - WALLET_NAME=${DVLA_WALLET_NAME}
      - WALLET_KEY=${DVLA_WALLET_KEY}
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./network/start-framework.sh:/scripts/start-framework.sh
    depends_on:
      - ngrok

  controller.dvla:
    build:
      context: dvla
    environment:
      - SERVER_PORT=8002
      - FRAMEWORK_HOST=framework.dvla
      - FRAMEWORK_PORT=8001
      - FRAMEWORK_SECRET=${DVLA_ADMIN_SECRET}
    ports:
      - "8002:8002"
